### ISSUE TITLE
unet = vxm.networks.unet_core(vol_shape, nb_enc_features, nb_dec_features); AttributeError: module 'voxelmorph.tf.networks' has no attribute 'unet_core'

### ISSUE THREAD

**Issue by lw505** [learn2reg/tutorials2019#9]
please tell me how to slove this question,thanks.

**Comment by adalca** [comment]
@lw505 thanks for your question. We're addressing it at this other board where you asked the same question: https://github.com/voxelmorph/voxelmorph/issues/289

**Comment by lw505** [comment]
Thank you very much for your help. I'll try your new code




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Adrian ***@***.***&gt;; 
发送时间: 2021年4月1日(星期四) 晚上8:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [learn2reg/tutorials2019] unet = vxm.networks.unet_core(vol_shape, nb_enc_features, nb_dec_features); AttributeError: module &#39;voxelmorph.tf.networks&#39; has no attribute &#39;unet_core&#39; (#9)





 
@lw505 thanks for your question. We're addressing it at this other board where you asked the same question: voxelmorph/voxelmorph#289
